name: subscription_commerce
version: '1.0.0'
config-version: 2
profile: subscription_commerce
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]
models:
  subscription_commerce:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
