version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_unique_id
        tests: [not_null]
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: order_status
        tests:
          - accepted_values:
              values: ['approved','canceled','created','delivered','invoiced','processing','shipped','unavailable']
  - name: stg_payments
    columns:
      - name: payment_value
        tests: [not_null]
  - name: stg_subscription_cycles
    columns:
      - name: subscription_id
        tests: [not_null]
      - name: cycle_number
        tests: [not_null]
      - name: billing_amount
        tests: [not_null]
  - name: mart_cohort_retention
    columns:
      - name: retention_rate
        tests: [not_null]
  - name: mart_segment_retention
    columns:
      - name: retention_rate
        tests: [not_null]
